# =============================================================================
# Initial duplex data processing
# =============================================================================
#   all dcs.vcf files generated by duplex pipeline were cleaned up manually in
#       excel and saved as txt file
#
#   Hom      (Sample 3823):  1mo  vs  pre        (per replicate)
#   Hom;Mfn1 (Sample 4748):  1mo vs pre          (per replicate)
#
# Baseline: for replicate r, log2FC = log2( MUT_FREQ(tp, r) / MUT_FREQ(pre, r) )
#
# Filenames:  Cell_<sample>_<rep>_<timepoint>.dcs.txt   (rep = middle number)
#
# Outputs (per line + one combined summary):
#   hom_within_line_long.csv     mfn1_within_line_long.csv
#   hom_wide.csv                 mfn1_wide.csv
#   within_line_summary.csv
#   <line>_<rep>_shared_pre_1mo.csv   (per rep: variants called in BOTH that line's pre and 1mo)
# =============================================================================

library(dplyr)
library(purrr)
library(stringr)
library(tidyr)

# #############################################################################
#               ##                 CONFIG                           ##
# #############################################################################

project_dir <- "/path/to/files"

# ---- derived paths ----
input_dir     <- project_dir                          # Sec 1 in : holds Hom/ and Hom_Mfn1/ which hold the dcs.txt files
output_dir    <- file.path(project_dir, "output")     # Sec 1 out
vep_dir       <- file.path(project_dir, "VEP")        # Sec 2 : <sample>.csv + <sample>_all_anno.txt
selection_dir <- file.path(project_dir, "output2")    # Sec 3 in : merged, annotated per-replicate csvs
# #############################################################################

# -----------------------------------------------------------------------------
# General settings
# -----------------------------------------------------------------------------
MIN_MUT_FREQ <- 1e-6      # noise floor at that line's pre
MIN_COV      <- 100       # coverage floor at that line's pre

REPLICATES <- c("1", "2", "3")

# Each line: its sample number and the 1 month timepoint to compare vs pre.
LINES <- list(
  hom  = list(sample = "3823", timepoints = c("1mo")),
  mfn1 = list(sample = "4748", timepoints = c("1mo"))
)
# -----------------------------------------------------------------------------

dir.create(output_dir, showWarnings = FALSE, recursive = TRUE)
KEY_COLS <- c("CHROM", "POS", "REF", "ALT", "VARTYPE")

# =============================================================================
# Helpers
# =============================================================================
read_dcs <- function(filepath) {
  df <- read.delim(filepath, sep = "\t", header = TRUE,
                   check.names = FALSE, stringsAsFactors = FALSE)
  if (nrow(df) == 0) { warning("Skipping empty file: ", basename(filepath)); return(NULL) }
  names(df) <- str_replace_all(names(df), "\\s+", "_") %>% toupper()
  if ("TOTAL_NUC" %in% names(df)) df <- rename(df, COV = TOTAL_NUC)
  df %>% distinct(across(all_of(KEY_COLS)), .keep_all = TRUE)
}

# Match filename directly, so folder spelling (1_mo vs 1mo) is irrelevant
find_file <- function(all_files, sample, rep, tp_label) {
  pat  <- sprintf("^cell_%s_%s_%s\\.dcs\\.txt$", sample, rep, tp_label)
  hits <- all_files[str_detect(tolower(basename(all_files)), pat)]
  if (length(hits) == 0) return(NULL)
  if (length(hits) > 1)
    warning(sprintf("Multiple files match sample=%s rep=%s tp=%s: %s",
                    sample, rep, tp_label, paste(basename(hits), collapse = ", ")))
  hits[1]
}

safe_log2fc <- function(num, den) {
  case_when(
    is.na(num) | is.na(den) ~ NA_real_,
    num == 0   & den == 0   ~ NA_real_,
    den == 0   & num > 0    ~  Inf,
    num == 0   & den > 0    ~ -Inf,
    TRUE ~ log2(num / den)
  )
}

# =============================================================================
# Build one line x one replicate: pre + 1mo timepoint, log2FC vs own pre
# =============================================================================
build_line_rep <- function(line_name, spec, rep, all_files) {
  tp_labels <- c("pre", spec$timepoints)
  
  series <- setNames(map(tp_labels, function(tp) {
    f <- find_file(all_files, spec$sample, rep, tp)
    if (is.null(f)) { message(sprintf("  [MISSING] %s rep%s / %s", line_name, rep, tp)); return(NULL) }
    message(sprintf("  [OK] %-4s rep%s / %-3s -> %s", line_name, rep, tp, basename(f)))
    df <- read_dcs(f); if (is.null(df)) return(NULL)
    df %>% select(all_of(KEY_COLS), MUT_FREQ, COV)
  }), tp_labels)
  
  if (is.null(series[["pre"]])) {
    warning(sprintf("%s rep%s: no pre (Sample %s) — skipping", line_name, rep, spec$sample))
    return(NULL)
  }
  
  renamed <- imap(series, function(df, tp) {
    if (is.null(df)) return(NULL)
    df %>% rename(!!paste0("MUT_FREQ_", tp) := MUT_FREQ,
                  !!paste0("COV_",      tp) := COV)
  }) %>% compact()
  
  joined <- reduce(renamed, full_join, by = KEY_COLS)
  
  # guarantee every expected column exists
  for (tp in tp_labels) for (pfx in c("MUT_FREQ_", "COV_")) {
    cc <- paste0(pfx, tp); if (!cc %in% names(joined)) joined[[cc]] <- NA_real_
  }
  
  # filter on THIS line's own pre
  joined <- joined %>%
    filter(!is.na(MUT_FREQ_pre),
           MUT_FREQ_pre >= MIN_MUT_FREQ,
           is.na(COV_pre) | COV_pre >= MIN_COV)
  
  # log2FC of 1mo timepoint vs this line/rep's own pre
  for (tp in spec$timepoints) {
    joined[[paste0("log2FC_", tp)]] <-
      safe_log2fc(joined[[paste0("MUT_FREQ_", tp)]], joined[["MUT_FREQ_pre"]])
  }
  
  joined$line      <- line_name
  joined$replicate <- paste0("rep", rep)
  joined
}

# =============================================================================
# MAIN
# =============================================================================
all_files <- list.files(input_dir, pattern = "\\.dcs\\.txt$",
                        full.names = TRUE, recursive = TRUE)
message("Found ", length(all_files), " .dcs.txt files under ", input_dir)

summary_all <- list()

for (line_name in names(LINES)) {
  spec <- LINES[[line_name]]
  message(sprintf("\n=== Line: %s (Sample %s) ===", line_name, spec$sample))
  
  rep_tbls <- map(REPLICATES, ~ build_line_rep(line_name, spec, .x, all_files)) %>% compact()
  if (length(rep_tbls) == 0) { warning("No tables built for ", line_name); next }
  line_tbl <- bind_rows(rep_tbls)
  message(sprintf("  %s: %d variant-rows across %d replicates",
                  line_name, nrow(line_tbl), length(rep_tbls)))
  
  # ---- LONG output ----
  long_cols <- c(KEY_COLS, "replicate", "MUT_FREQ_pre",
                 unlist(lapply(spec$timepoints, function(tp)
                   c(paste0("MUT_FREQ_", tp), paste0("COV_", tp), paste0("log2FC_", tp)))))
  write.csv(line_tbl %>% select(all_of(long_cols)),
            file.path(output_dir, sprintf("exp_%s_within_line_long.csv", line_name)),
            row.names = FALSE)
  
  # ---- WIDE output (one column per replicate, per timepoint; Prism-ready) ----
  wide_tbl <- Reduce(function(acc, tp) {
    col <- paste0("log2FC_", tp)
    w <- line_tbl %>%
      transmute(across(all_of(KEY_COLS)), replicate = replicate, val = .data[[col]]) %>%
      pivot_wider(names_from  = replicate, values_from = val,
                  names_glue  = paste0(col, "_{replicate}"))
    if (is.null(acc)) w else full_join(acc, w, by = KEY_COLS)
  }, spec$timepoints, init = NULL) %>%
    arrange(CHROM, POS, REF, ALT)
  write.csv(wide_tbl,
            file.path(output_dir, sprintf("exp_%s_wide.csv", line_name)),
            row.names = FALSE)
  
  # ---- SUMMARY (per timepoint x replicate) ----
  for (tp in spec$timepoints) {
    col <- paste0("log2FC_", tp)
    s <- line_tbl %>%
      group_by(replicate) %>%
      summarise(
        line          = line_name,
        timepoint     = tp,
        n             = sum(is.finite(.data[[col]])),
        median_log2FC = median(.data[[col]][is.finite(.data[[col]])]),
        pct_neg       = mean(.data[[col]] < 0, na.rm = TRUE) * 100,
        p_vs_zero     = tryCatch(
          wilcox.test(.data[[col]][is.finite(.data[[col]])],
                      mu = 0, alternative = "less")$p.value,
          error = function(e) NA_real_),
        .groups = "drop"
      ) %>%
      select(line, timepoint, replicate, n, median_log2FC, pct_neg, p_vs_zero)
    summary_all[[paste(line_name, tp, sep = "_")]] <- s
  }
  
  # ---- SHARED set: mutations identified in BOTH pre and 1mo ----------------
  # One file per replicate, containing only variants with a non-NA frequency
  # in this line's pre AND its 1mo for that replicate. Keeps the frequencies,
  # coverage, and the pre -> 1mo log2FC for the shared set.
  if ("1mo" %in% spec$timepoints) {
    keep_cols <- c(KEY_COLS,
                   "MUT_FREQ_pre", "COV_pre",
                   "MUT_FREQ_1mo", "COV_1mo", "log2FC_1mo")
    for (rp in sort(unique(line_tbl$replicate))) {
      both <- line_tbl %>%
        filter(replicate == rp,
               !is.na(MUT_FREQ_pre), !is.na(MUT_FREQ_1mo)) %>%
        select(all_of(keep_cols)) %>%
        arrange(CHROM, POS, REF, ALT)
      write.csv(both,
                file.path(output_dir,
                          sprintf("exp_%s_%s_shared_pre_1mo.csv", line_name, rp)),
                row.names = FALSE)
      message(sprintf("  %s %s: %d mutations shared by pre & 1mo",
                      line_name, rp, nrow(both)))
    }
  }
}

summary_stats <- bind_rows(summary_all) %>% arrange(line, timepoint, replicate)
write.csv(summary_stats,
          file.path(output_dir, "exp_within_line_summary.csv"),
          row.names = FALSE)

message("\n--- Within-line summary (log2FC vs own pre; negative = mutation lost) ---")
print(summary_stats)
message(sprintf("\n=== Done. All files written to: %s ===", output_dir))




# =============================================================================
# Post-VEP run (on Ensembl Website) merge
# =============================================================================
#   for each condition (hom or mfn1), use the within_line_long csv file, and
#     manually generate files for each replicate, save as <sample>.csv.
#     Organize them as vcf files, then run them through VEP on Ensembl's website
#     and save them as <sample>_all_anno.txt. Then follow below to merge the
#     annotation file with the <sample>.csv file.
# =============================================================================

# ---- 1. Input folder (set at the top, in CONFIG) ----
folder <- vep_dir

# ---- 2. Samples to process ----
# For each sample the script expects:
#   <sample>.csv                 (variant table)
#   <sample>_all_anno.txt        (VEP annotation, tab-delimited)
# and writes:
#   <sample>_all_anno_merge.csv
samples <- c("hom_mfn1_rep1", "hom_mfn1_rep2", "hom_mfn1_rep3",
             "hom_rep1",      "hom_rep2",      "hom_rep3")

# ---- 3. annotation columns to keep, in the merge column order ----
keys <- c("CHROM", "POS", "REF", "ALT")

anno_cols <- c("Consequence","IMPACT","SYMBOL","Gene","Feature_type","Feature",
               "BIOTYPE","EXON","INTRON","HGVSc","HGVSp","cDNA_position",
               "CDS_position","Protein_position","Amino_acids","Codons",
               "Existing_variation","DISTANCE","STRAND","FLAGS","SYMBOL_SOURCE",
               "HGNC_ID","MANE","MANE_SELECT","MANE_PLUS_CLINICAL","TSL","APPRIS",
               "CCDS","ENSP","SWISSPROT","TREMBL","UNIPARC","UNIPROT_ISOFORM",
               "SIFT","HGVS_OFFSET","CLIN_SIG","SOMATIC","PHENO","MOTIF_NAME",
               "MOTIF_POS","HIGH_INF_POS","MOTIF_SCORE_CHANGE","TRANSCRIPTION_FACTORS",
               "BLOSUM62","NMD","PHENOTYPES")

# ---- 4. merge function ----
merge_one <- function(sample) {
  var_file  <- file.path(folder, paste0(sample, ".csv"))
  anno_file <- file.path(folder, paste0(sample, "_all_anno.txt"))
  out_file  <- file.path(folder, paste0(sample, "_all_anno_merge.csv"))
  
  if (!file.exists(var_file) || !file.exists(anno_file)) {
    cat("SKIP", sample, "- missing .csv or _all_anno.txt\n")
    return(invisible(NULL))
  }
  
  var  <- read.csv(var_file, colClasses = "character",
                   check.names = FALSE, fileEncoding = "UTF-8-BOM")
  anno <- read.delim(anno_file, colClasses = "character", check.names = FALSE)
  
  anno   <- anno[, c(keys, anno_cols)]          # keep + order the annotation columns
  merged <- left_join(var, anno, by = keys)     # keep every variant
  
  write.csv(merged, out_file, row.names = FALSE, na = "")
  cat("OK  ", sample, "| variant rows:", nrow(var),
      "| merged rows:", nrow(merged), "| columns:", ncol(merged), "\n")
}

# ---- 5. run all ----
for (s in samples) merge_one(s)




# ============================================================================
#  mtDNA selection analysis  —  used to generate fig 6D and 6E
#
#  Generates :
#    (1) Unified impact-level table - one CSV per replicate
#    (2) Frequency-adjusted functional-class table - one summary CSV
#
#  Assumptions about file names / columns :
#    - Files whose NAME contains "mfn1"  -> Mfn1-KO group; all others -> Control.
#    - Every file has: CHROM, POS, REF, ALT, MUT_FREQ_pre, IMPACT, Consequence,
#                      SYMBOL, BIOTYPE.
# ============================================================================

# ---- 1. Input folder (set at the top, in CONFIG) ----
input_folder <- selection_dir

# ---- 2. additional settings ----
group_keyword <- "mfn1"   # filenames containing this word are the KO group
baseline_thr  <- 4e-5     # ignore variants below this baseline frequency
dloop_start   <- 15423    # positions >= this are the non-coding control region

# --- make sure data.table is available --------
if (!requireNamespace("data.table", quietly = TRUE)) install.packages("data.table")
library(data.table)

output_folder <- file.path(input_folder, "output3")
dir.create(output_folder, showWarnings = FALSE)
SEVERITY <- c(HIGH = 0, MODERATE = 1, LOW = 2, MODIFIER = 3)
CLASSES  <- c("truncating", "missense", "tRNA", "rRNA", "D-loop")  # vs synonymous

# --- 3. helper functions --------
load_variants <- function(path) {
  a <- fread(path)
  a[, .sev := SEVERITY[IMPACT]]
  setorder(a, .sev)
  a <- a[!duplicated(a[, .(CHROM, POS, REF, ALT)])]   # one row per unique variant
  a[, .sev := NULL][]
}

normalize_dloop <- function(a) {
  a <- copy(a)
  is_dloop <- a$SYMBOL %in% c("D-Loop", "D-LOOP") |
    a$Consequence %in% c("intergenic","intergenic_variant","D-Loop","D-LOOP","D_Loop") |
    suppressWarnings(as.numeric(a$POS)) >= dloop_start
  a[is_dloop, `:=`(Consequence = "intergenic", SYMBOL = "D-Loop", IMPACT = "MODIFIER")]
  a[]
}

# Unified survival score: log2FC if the variant survived, if not, the detection-limit
# floor if it was completely lost.  Also returns the median coverage used.
add_unified <- function(a, l2col, covcol) {
  a   <- copy(a)
  pre <- suppressWarnings(as.numeric(a$MUT_FREQ_pre))
  a   <- a[pre > baseline_thr]
  pre <- pre[pre > baseline_thr]
  l2  <- suppressWarnings(as.numeric(a[[l2col]]))
  cov <- suppressWarnings(as.numeric(a[[covcol]]))
  median_cov  <- median(cov, na.rm = TRUE)
  floor_score <- log2((0.5 / median_cov) / pre)            # detection-limit floor
  a[, u      := ifelse(is.na(l2), floor_score, l2)]
  a[, lost   := is.na(l2)]
  a[, logpre := log10(pre)]
  attr(a, "median_cov") <- median_cov
  a[]
}

categorize_functional <- function(biotype, consequence, pos) {
  if (identical(biotype, "Mt_tRNA")) return("tRNA")
  if (identical(biotype, "Mt_rRNA")) return("rRNA")
  cq <- as.character(consequence)
  if (grepl("stop_gained|frameshift|stop_lost|start_lost", cq)) return("truncating")
  if (grepl("missense",   cq)) return("missense")
  if (grepl("synonymous", cq)) return("synonymous")
  if (grepl("intergenic", cq) || (!is.na(pos) && as.numeric(pos) >= dloop_start)) return("D-loop")
  "other"
}

# (1) unified impact-level table for each file
unified_impact_table <- function(a, l2col, covcol) {
  d   <- normalize_dloop(add_unified(a, l2col, covcol))
  syn <- d[Consequence == "synonymous_variant", u]
  syn_median <- median(syn, na.rm = TRUE)
  syn_mad    <- median(abs(syn - syn_median), na.rm = TRUE)   # raw (unscaled) MAD
  out <- d[, .(n_variants = .N,
               loss_rate = mean(lost),
               median_unified_survival = median(u),
               mean_unified_survival   = mean(u)), by = IMPACT]
  out[, survival_vs_syn := median_unified_survival - syn_median]
  out[, selection_score := (median_unified_survival - syn_median) / syn_mad]
  setorder(out, selection_score)   # most depleted (most negative) first
  out[]
}

# (2) frequency-adjusted functional-class coefficients for each file
functional_coeffs <- function(a, l2col, covcol) {
  d <- add_unified(a, l2col, covcol)
  d[, cat := mapply(categorize_functional, BIOTYPE, Consequence, POS)]
  d <- d[cat %in% c("synonymous", CLASSES)]
  d[, cat := relevel(factor(cat), ref = "synonymous")]
  fit <- lm(u ~ cat + logpre, data = d)                      # frequency-adjusted
  setNames(coef(fit)[paste0("cat", CLASSES)], CLASSES)
}

# --- 4. auto-detect files and groups --------
files <- list.files(input_folder, pattern = "\\.csv$", full.names = TRUE)
files <- files[!grepl("/output3/", files)]
if (length(files) == 0) stop("No CSV files found in input_folder. Check the path.")

# infer each files group (from its log2FC_* columns)
info <- rbindlist(lapply(files, function(f) {
  hdr <- names(fread(f, nrows = 0))
  tps <- sub("^log2FC_", "", grep("^log2FC_", hdr, value = TRUE))
  tps <- tps[paste0("COV_", tps) %in% hdr]
  data.table(file = f,
             group = ifelse(grepl(group_keyword, basename(f), ignore.case = TRUE),
                            "Mfn1-KO", "Control"),
             timepoint = if (length(tps)) list(tps) else list(character(0)))
}))

cat("\nFound", length(files), "file(s):\n")
for (i in seq_len(nrow(info)))
  cat(sprintf("  %-40s  group=%-8s  timepoints=%s\n",
              basename(info$file[i]), info$group[i],
              paste(info$timepoint[[i]], collapse = ", ")))
cat("\n(If the group is wrong, rename files so KO files contain '", group_keyword,
    "'.)\n\n", sep = "")


# --- 5A: write unified impact tables --------

cat("Writing unified impact tables + median coverage per sample:\n")
for (i in seq_len(nrow(info))) {
  a <- load_variants(info$file[i])
  for (tp in info$timepoint[[i]]) {
    l2col <- paste0("log2FC_", tp); covcol <- paste0("COV_", tp)
    d_tmp <- add_unified(a, l2col, covcol)
    tab   <- unified_impact_table(a, l2col, covcol)
    lbl   <- paste0(sub("\\.csv$", "", basename(info$file[i])), "_", tp)
    fwrite(tab, file.path(output_folder, paste0(lbl, "_UNIFIED_impact.csv")))
    cat(sprintf("  %-45s  median_coverage = %s\n", lbl,
                format(round(attr(d_tmp, "median_cov")), big.mark = ",")))
  }
}

# --- 5B: frequency-adjusted functional-class table --------

# group files by (group, timepoint); fit each replicate, summarize across reps
combos <- unique(rbindlist(lapply(seq_len(nrow(info)), function(i)
  if (length(info$timepoint[[i]]))
    data.table(group = info$group[i], timepoint = info$timepoint[[i]]))))

func_rows <- list(); coef_store <- list()
for (k in seq_len(nrow(combos))) {
  g <- combos$group[k]; tp <- combos$timepoint[k]
  fs <- info$file[info$group == g & sapply(info$timepoint, function(x) tp %in% x)]
  mat <- sapply(fs, function(f)
    functional_coeffs(load_variants(f), paste0("log2FC_", tp), paste0("COV_", tp)))
  if (is.null(dim(mat))) mat <- matrix(mat, ncol = 1)
  coef_store[[paste(g, tp)]] <- mat
  for (c in CLASSES) {
    v <- mat[c, ]
    func_rows[[length(func_rows) + 1]] <- data.table(
      timepoint = tp, group = g, functional_class = c,
      mean = mean(v),
      sem  = if (length(v) > 1) sd(v) / sqrt(length(v)) else NA_real_,
      n_reps = length(v))
  }
}

func_tab <- rbindlist(func_rows)
fwrite(func_tab, file.path(output_folder, "functional_unified_freqadj.csv"))

cat("\nDone. Outputs are in:\n  ", output_folder, "\n", sep = "")
cat("  - one *_UNIFIED_impact.csv per replicate\n")
cat("  - functional_unified_freqadj.csv\n")
